blueprint:
  name: "Svitlo Live: Сповіщення + Telegram"
  description: "Надсилає push та Telegram повідомлення про оновлення графіків АБО введення екстрених відключень. Має вбудовану затримку 50 хв на скасування аварії."
  domain: automation
  source_url: https://github.com/chaichuk/svitlo_live

  input:
    schedule_calendar:
      name: Календар Svitlo Live
      selector:
        entity:
          domain: calendar
          integration: svitlo_live

    schedule_updated_sensor:
      name: Сенсор оновлення розкладу
      description: "Оберіть sensor 'Schedule updated' для цього регіону"
      selector:
        entity:
          domain: sensor
          integration: svitlo_live

    emergency_sensor:
      name: Сенсор аварійних відключень
      description: "Оберіть binary_sensor 'Emergency outages' (якщо є)"
      default: {}
      selector:
        entity:
          domain: binary_sensor
          integration: svitlo_live

    mobile_targets:
      name: Мобільні пристрої (HA App)
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    telegram_chat_id:
      name: Telegram Chat ID
      description: "ID чату/групи. Можна декілька через кому. Пусто = без Telegram."
      default: ""
      selector:
        text:

    title_text:
      name: Заголовок (стандартний)
      default: "⚠️ Оновлено графіки відключень!"
      selector:
        text:

    location_name:
      name: Локація
      default: "Дім"
      selector:
        text:

    storage_helper:
      name: Helper для збереження
      description: "Text helper для збереження стану (щоб не було дублів)"
      selector:
        entity:
          domain: input_text

    text_output:
      name: Helper для тексту розкладу (необов'язково)
      description: "Сюди буде записуватись готовий текст"
      default: {}
      selector:
        entity:
          domain: input_text

    send_persistent_notification:
      name: Створювати persistent_notification в HA
      default: true
      selector:
        boolean:

    send_on_first_run:
      name: Надсилати сповіщення при першому запуску
      default: true
      selector:
        boolean:

mode: restart

variables:
  cal_entity: !input schedule_calendar
  emergency_entity: !input emergency_sensor
  mobile_targets: !input mobile_targets
  telegram_chat_id: !input telegram_chat_id
  base_title: !input title_text
  location_name: !input location_name
  storage_helper: !input storage_helper
  text_output: !input text_output
  send_persistent_notification: !input send_persistent_notification
  send_on_first_run: !input send_on_first_run

  # Перевіряємо статус аварії
  is_emergency: >-
    {% if emergency_entity %}
      {{ is_state(emergency_entity, 'on') }}
    {% else %}
      false
    {% endif %}

  # Визначаємо, чи спрацював тригер через зміну аварійного статусу
  triggered_by_emergency: >-
    {{ trigger.entity_id is defined and trigger.entity_id == emergency_entity }}

trigger:
  - platform: state
    entity_id: !input schedule_updated_sensor
  - platform: state
    entity_id: !input emergency_sensor

condition:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
  # При аварії ігноруємо часові рамки (важливо знати про це і вночі)
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ triggered_by_emergency }}"
      - condition: time
        after: "05:00:00"
        before: "23:40:00"

action:
  - if:
      - condition: template
        value_template: "{{ triggered_by_emergency and not is_emergency }}"
    then:
      - delay: 
          minutes: 50

  # 1) Отримуємо події календаря
  - service: calendar.get_events
    target:
      entity_id: !input schedule_calendar
    data:
      start_date_time: "{{ today_at('00:00').isoformat() }}"
      end_date_time: "{{ (today_at('00:00') + timedelta(days=2) - timedelta(seconds=1)).isoformat() }}"
    response_variable: cal_resp

  - variables:
      raw_events: >-
        {% set r = cal_resp %}{% set k = cal_entity %}
        {% if r is mapping and (k in r) and (r[k] is mapping) and ('events' in r[k]) %}
          {{ r[k]['events'] | sort(attribute='start') }}
        {% else %}[]{% endif %}

      # Формуємо підпис графіка
      schedule_signature: >-
        {%- set ns = namespace(sig='') -%}
        {%- for e in raw_events -%}
          {%- set s = as_datetime(e.start).strftime('%y%m%d%H%M') -%}
          {%- set t = as_datetime(e.end).strftime('%y%m%d%H%M') -%}
          {%- set ns.sig = ns.sig ~ s ~ t -%}
        {%- endfor -%}
        {{ ("c=" ~ (raw_events|count|string) ~ ";" ~ ns.sig) | trim }}

      old_signature: "{{ states(storage_helper) | default('') }}"

      # Перевірка змін
      has_changed: >-
        {% if triggered_by_emergency %}
          true
        {% elif is_emergency %}
          false
        {% elif send_on_first_run %}
          {{ schedule_signature[-255:] != old_signature }}
        {% else %}
          {{ schedule_signature[-255:] != old_signature and old_signature != '' }}
        {% endif %}

  - if:
      - condition: template
        value_template: "{{ has_changed }}"
    then:
      - variables:
          # --- Формування тексту ---
          events_today: >-
            {% set today = now().astimezone(now().tzinfo).date() %}
            {% set current_time = now().astimezone(now().tzinfo) %}
            {% set ns = namespace(events=[]) %}
            {% for e in raw_events %}
              {% set e_start = as_datetime(e.start).astimezone(now().tzinfo) %}
              {% set e_end = as_datetime(e.end).astimezone(now().tzinfo) %}
              {% if e_start.date() == today and e_end > current_time %}
                {% set ns.events = ns.events + [e] %}
              {% endif %}
            {% endfor %}
            {{ ns.events }}

          events_tomorrow: >-
            {% set tomorrow = (now().astimezone(now().tzinfo) + timedelta(days=1)).date() %}
            {% set ns = namespace(events=[]) %}
            {% for e in raw_events %}
              {% if as_datetime(e.start).astimezone(now().tzinfo).date() == tomorrow %}
                {% set ns.events = ns.events + [e] %}
              {% endif %}
            {% endfor %}
            {{ ns.events }}

          # --- ДИНАМІЧНИЙ ЗАГОЛОВОК ---
          final_title: >-
            {% if is_emergency %}
              🚨 ЕКСТРЕНІ ВІДКЛЮЧЕННЯ!
            {% elif triggered_by_emergency and not is_emergency %}
              ✅ Екстрені відключення завершено
            {% else %}
              {{ base_title }}
            {% endif %}

          # --- ТІЛО ПОВІДОМЛЕННЯ (Мобільний) ---
          body: >-
            📍 {{ location_name }}

            {% if is_emergency -%}
            ⛔️ УВАГА! Введені екстрені/аварійні відключення.
            Графіки наразі НЕ ДІЮТЬ. Світло може зникати без попередження.
            {%- else -%}
            
            {% if events_today | length > 0 -%}
            📅 СЬОГОДНІ ({{ now().strftime('%d.%m') }})
            {% for e in events_today -%}
            {%- set s = as_datetime(e.start).astimezone(now().tzinfo) -%}
            {%- set end = as_datetime(e.end).astimezone(now().tzinfo) -%}
            ❌ {{ s.strftime('%H:%M') }} ━ {{ end.strftime('%H:%M') }}
            {% endfor -%}
            {%- else -%}
            📅 СЬОГОДНІ: ⚡ далі без відключень
            {%- endif %}

            {% if events_tomorrow | length > 0 -%}
            📅 ЗАВТРА ({{ (now() + timedelta(days=1)).strftime('%d.%m') }})
            {% for e in events_tomorrow -%}
            {%- set s2 = as_datetime(e.start).astimezone(now().tzinfo) -%}
            {%- set e2 = as_datetime(e.end).astimezone(now().tzinfo) -%}
            ❌ {{ s2.strftime('%H:%M') }} ━ {{ e2.strftime('%H:%M') }}
            {% endfor -%}
            {%- endif %}
            {%- endif %}

          # --- ТІЛО ПОВІДОМЛЕННЯ (Telegram) ---
          body_text: |-
            📍 {{ location_name }}

            {% if is_emergency -%}
            🚨 <b>УВАГА! Введено екстрені відключення!</b>
            
            За розпорядженням Укренерго введені аварійні відключення.
            ⚠️ <b>Графіки планових відключень наразі НЕ ДІЮТЬ.</b>
            Світло може вимикатися та вмикатися без попередження для стабілізації енергосистеми.
            {%- else -%}
            
            {% if events_today | length > 0 -%}
            📅 СЬОГОДНІ ({{ now().strftime('%d.%m.%Y') }})
            {% for e in events_today -%}
            {%- set s = as_datetime(e.start).astimezone(now().tzinfo) -%}
            {%- set end = as_datetime(e.end).astimezone(now().tzinfo) -%}
            ❌ {{ s.strftime('%H:%M') }} ━ {{ end.strftime('%H:%M') }}
            {% endfor -%}
            {%- else -%}
            📅 СЬОГОДНІ ({{ now().strftime('%d.%m.%Y') }}): ⚡ далі без відключень
            {%- endif %}

            {% if events_tomorrow | length > 0 -%}
            📅 ЗАВТРА ({{ (now() + timedelta(days=1)).strftime('%d.%m.%Y') }})
            {% for e in events_tomorrow -%}
            {%- set s2 = as_datetime(e.start).astimezone(now().tzinfo) -%}
            {%- set e2 = as_datetime(e.end).astimezone(now().tzinfo) -%}
            ❌ {{ s2.strftime('%H:%M') }} ━ {{ e2.strftime('%H:%M') }}
            {% endfor -%}
            {%- endif %}
            {%- endif %}

      # 2.1) Сповіщення на телефони
      - repeat:
          for_each: !input mobile_targets
          sequence:
            - variables:
                svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
            - service: "{{ svc }}"
              data:
                title: "{{ final_title }}"
                message: "{{ body }}"
                data:
                  priority: "{{ 'high' if is_emergency else 'high' }}"
                  tag: svitlo_changed
                  channel: "{{ 'Emergency' if is_emergency else 'General' }}"
                  notification_icon: "{{ 'mdi:alert-octagon' if is_emergency else 'mdi:calendar-check' }}"
                  color: "{{ '#FF0000' if is_emergency else '' }}"

      # 2.2) Telegram
      - if:
          - condition: template
            value_template: "{{ telegram_chat_id != '' }}"
        then:
          - service: telegram_bot.send_message
            data:
              target: >-
                {% if telegram_chat_id is string %}
                  {{ telegram_chat_id.split(',') | map('trim') | list }}
                {% else %}
                  {{ telegram_chat_id }}
                {% endif %}
              title: "{{ final_title }}"
              message: "{{ body_text }}"
              parse_mode: HTML

      # 2.3) Persistent notification
      - if:
          - condition: template
            value_template: "{{ send_persistent_notification }}"
        then:
          - service: persistent_notification.create
            data:
              title: "{{ final_title }}"
              message: "{{ body }}"
              notification_id: svitlo_changed

      # 2.4) Helper write
      - if:
          - condition: template
            value_template: "{{ text_output != {} }}"
        then:
          - service: input_text.set_value
            target:
              entity_id: !input text_output
            data:
              value: "{{ body_text[:255] }}"

  # 4) Зберігаємо підпис (ТІЛЬКИ якщо це НЕ аварія)
  - if:
      - condition: template
        value_template: "{{ not is_emergency }}"
    then:
      - service: input_text.set_value
        target:
          entity_id: !input storage_helper
        data:
          value: "{{ schedule_signature[-255:] }}"
